image:
  repository: xhofe/alist
  pullPolicy: IfNotPresent
  tag: 3.15.1@sha256:fd905df48c06cd5d6c3e1367072aea262d6fec32eccb2b10bf762a75c58ab520

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 5244
        port: 35244

persistence:
  data:
    enabled: true
    mountPath: "/opt/alist/data"

portal:
  enabled: true