image:
  repository: amilys/embyserver
  pullPolicy: IfNotPresent
  tag: latest@sha256:56f97c0a0ec93f39f06613a4bf5de01c33a370988277e2727ed2d91c5ba33a61

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 8096
        targetPort: 8096

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true