apiVersion: v2
dependencies:
- name: common
  repository: file://../../../library/common/2207.0.0
  version: 2207.0.0
description: NAS媒体库资源归集、整理自动化工具
home: https://github.com/sleikang/MediaServerTools 
icon: https://github.com/fluidicon.png
keywords:
- media
name: MediaServerTools
version: 1.0.1