apiVersion: v2
dependencies:
  - name: common
    repository: https://github.com/BenZinaDaze/charts
    version: 2207.0.0
description: Emby/Jellyfin/Plex 媒体中文自动同步
home: https://github.com/sleikang/MediaServerTools
icon: https://github.com/fluidicon.png
sources:
  - "https://github.com/sleikang/MediaServerTools"
name: mediaservertools
version: 1.0.1
