apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: common
  repository: file://../../../library/common/2207.0.0
  version: 2207.0.0
description: clash core
home: https://www.baidu.com
icon: https://raw.githubusercontent.com/Dreamacro/clash/master/docs/logo.png
keywords:
- tools
name: clash
version: 1.0.2
