image:
  repository: linuxserver/qbittorrent
  pullPolicy: IfNotPresent
  tag: 4.5.2-libtorrentv1@sha256:ad9697a1b694e87eb44040a2c8fdbdc301a185b7a9b662077ff42e6ab3aa1c28

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 38080
        targetPort: 38080
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 36881
        protocol: TCP
      torrentudp:
        enabled: true
        port: 36881
        protocol: UDP

persistence:
  config:
    enabled: true
    mountPath: "/config"

additionalVolumes:
  - name: qbittorrent-scripts
    emptyDir: {}
    ## When you want to enable automatic port configuration at startup, adjust this to:
    # configMap:
    #   name: <RELEASENAME>-scripts
    #   defaultMode: 511

additionalVolumeMounts:
  - mountPath: "/config/custom-cont-init.d"
    name: qbittorrent-scripts

portal:
  enabled: true