image:
  repository: superng6/qbittorrentee
  pullPolicy: IfNotPresent
  tag: 4.5.4.10@sha256:be92ecde9074e0ce72f3f0690caa3d3b864fb96fd3d477397f86cfdda8d341f6

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 6881
        protocol: TCP
      torrentudp:
        enabled: true
        port: 6881
        protocol: UDP

persistence:
  config:
    enabled: true
    mountPath: "/config"

additionalVolumes:
  - name: qbittorrent-scripts
    emptyDir: {}
    ## When you want to enable automatic port configuration at startup, adjust this to:
    # configMap:
    #   name: <RELEASENAME>-scripts
    #   defaultMode: 511

additionalVolumeMounts:
  - mountPath: "/config/custom-cont-init.d"
    name: qbittorrent-scripts

portal:
  enabled: true