image:
  repository: zerotier/zerotier
  pullPolicy: IfNotPresent
  tag: 1.10.6@sha256:e18d6af4d7cbc995f7e416c91433cf910e0971187f3bb29827b10ac708e1d921

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  capabilities:
    add:
      - NET_ADMIN

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  ZEROTIER_API_SECRET: ""
  ZEROTIER_IDENTITY_PUBLIC: ""
  ZEROTIER_IDENTITY_SECRET: ""

service:
  main:
    ports:
      main:
        protocol: UDP
        targetPort: 9993
        port: 10190

persistence:
  config:
    enabled: true
    mountPath: "/var/lib/zerotier-one"
  tun:
    enabled: true
    type: hostPath
    hostPath: /dev/net/tun
    mountPath: /dev/net/tun
    hostPathType: ""
    readOnly: false

portal:
  enabled: false