apiVersion: v2
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
home: https://truecharts.org/charts/stable/jackett
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jackett.png
sources:

  - https://github.com/Jackett/Jackett
name: jackett
version: 1.0.1