apiVersion: v2
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 11.1.2
description: API Support for your favorite torrent trackers.
home: https://truecharts.org/charts/stable/jackett
icon: https://truecharts.org/img/hotlink-ok/chart-icons/jackett.png
keywords:
  - jackett
  - torrent
  - usenet
kubeVersion: ">=1.16.0-0"
name: jackett
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/jackett
  - https://ghcr.io/onedr0p/jackett
  - https://github.com/Jackett/Jackett
type: application
version: 1.0.1