image:
  repository: lovechen/embyserver
  pullPolicy: IfNotPresent
  tag: 4.7.11.0@sha256:7901a5190c58a393820b75db80e0a536b29ea1049f02319aaf8075f14a867e83

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 8096
        targetPort: 8096

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true