image:
  repository: tccr.io/truecharts/ddns-go
  pullPolicy: IfNotPresent
  tag: v5.0.4@sha256:7f3130b919a5a9619d7ba7e50a70b2f2617478f59f9c5721d59d7e4ef30684d9

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 9876
        port: 9876

persistence:
  data:
    enabled: true
    mountPath: "/root"

portal:
  enabled: true