image:
  repository: linuxserver/jackett
  pullPolicy: IfNotPresent
  tag: 0.20.4078@sha256:5295d4ce64cc358ec9e47de3cf83813cc4ba2d143c30a439776391792a5c0150

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        protocol: HTTP
        targetPort: 9117
        port: 9117

probes:
  liveness:
    path: "/UI/Login"

  readiness:
    path: "/UI/Login"

  startup:
    path: "/UI/Login"

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
